definitions:
  auth.LoginCredentials:
    properties:
      login:
        minLength: 3
        type: string
      password:
        maxLength: 72
        minLength: 6
        type: string
    required:
    - login
    - password
    type: object
  auth.RegisterCredentials:
    properties:
      confirmPassword:
        minLength: 6
        type: string
      email:
        type: string
      password:
        minLength: 6
        type: string
      username:
        minLength: 3
        type: string
    required:
    - confirmPassword
    - email
    - password
    - username
    type: object
  auth.TokenSuccessResponse:
    properties:
      data:
        $ref: '#/definitions/auth.Tokens'
      success:
        default: true
        type: boolean
    required:
    - data
    - success
    type: object
  auth.Tokens:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
    required:
    - accessToken
    - refreshToken
    type: object
  chat.CreateChatSuccessResponse:
    properties:
      data:
        $ref: '#/definitions/chat.createChatResponse'
      success:
        default: true
        type: boolean
    type: object
  chat.createChatParams:
    properties:
      name:
        type: string
      type:
        type: string
    type: object
  chat.createChatResponse:
    properties:
      id:
        type: string
    type: object
  httputil.ErrorBody:
    properties:
      code:
        type: string
      fields: {}
      message:
        type: string
    type: object
  httputil.ErrorResponse:
    properties:
      error:
        $ref: '#/definitions/httputil.ErrorBody'
      success:
        default: false
        type: boolean
    type: object
  httputil.Response:
    properties:
      success:
        default: true
        type: boolean
    type: object
  message.MessagesSuccessResponse:
    properties:
      data:
        $ref: '#/definitions/message.messagesResponse'
      success:
        default: true
        type: boolean
    type: object
  message.messagesResponse:
    properties:
      messages:
        items:
          $ref: '#/definitions/model.Message'
        type: array
      nextCursor:
        type: string
    type: object
  model.Message:
    properties:
      chatId:
        type: string
      content:
        type: string
      createdAt:
        type: string
      id:
        type: string
      sender:
        $ref: '#/definitions/model.User'
    required:
    - chatId
    - content
    - createdAt
    - id
    - sender
    type: object
  model.User:
    properties:
      avatarUrl:
        type: string
      email:
        type: string
      emailVerified:
        type: boolean
      id:
        type: string
      username:
        type: string
    required:
    - avatarUrl
    - email
    - emailVerified
    - id
    - username
    type: object
  user.SuccessResponse:
    properties:
      data:
        $ref: '#/definitions/model.User'
      success:
        default: true
        type: boolean
    required:
    - data
    - success
    type: object
  user.sendVerificationCodeRequest:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  user.updateEmailRequest:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  user.updatePasswordRequest:
    properties:
      currentPassword:
        minLength: 6
        type: string
      newPassword:
        minLength: 6
        type: string
    required:
    - currentPassword
    - newPassword
    type: object
info:
  contact: {}
  title: Lunar API
  version: 1.0.0
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Login credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/auth.LoginCredentials'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.TokenSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
      summary: Login a user
      tags:
      - auth
  /auth/logout:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httputil.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
      summary: Logout a user
      tags:
      - auth
  /auth/refresh:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.TokenSuccessResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
      summary: Refresh access token
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: Registration credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/auth.RegisterCredentials'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.TokenSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
      summary: Register a new user
      tags:
      - auth
  /chats:
    post:
      consumes:
      - application/json
      parameters:
      - description: Chat creation params
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/chat.createChatParams'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/chat.CreateChatSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Create a new chat
      tags:
      - chat
  /chats/{chatID}:
    post:
      parameters:
      - description: Chat ID
        in: path
        name: chatID
        required: true
        type: string
      responses:
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Join current user to chat
      tags:
      - chat
  /chats/{chatID}/messages:
    get:
      parameters:
      - description: Chat ID
        in: path
        name: chatID
        required: true
        type: string
      - description: Limit
        in: query
        name: limit
        type: integer
      - description: Cursor
        in: query
        name: cursor
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/message.MessagesSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
      security:
      - BearerAuth: []
      summary: List messages in a chat
      tags:
      - message
  /users/me:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get current user
      tags:
      - user
  /users/me/avatar:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: Avatar file
        in: formData
        name: avatar
        required: true
        type: file
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Upload user avatar
      tags:
      - user
  /users/me/email:
    put:
      consumes:
      - application/json
      parameters:
      - description: Email update request
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/user.updateEmailRequest'
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Update user email
      tags:
      - user
  /users/me/password:
    put:
      consumes:
      - application/json
      parameters:
      - description: Password change request
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/user.updatePasswordRequest'
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Change user password
      tags:
      - user
  /users/me/verification-code:
    post:
      consumes:
      - application/json
      parameters:
      - description: Verification request
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/user.sendVerificationCodeRequest'
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Send verification code
      tags:
      - user
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
