definitions:
  auth.LoginCredentials:
    properties:
      login:
        maxLength: 255
        minLength: 3
        type: string
      password:
        maxLength: 72
        minLength: 6
        type: string
    required:
    - login
    - password
    type: object
  auth.RegisterCredentials:
    properties:
      confirmPassword:
        maxLength: 72
        minLength: 6
        type: string
      email:
        maxLength: 255
        type: string
      password:
        maxLength: 72
        minLength: 6
        type: string
      username:
        maxLength: 32
        minLength: 3
        type: string
    required:
    - confirmPassword
    - email
    - password
    - username
    type: object
  auth.ResendVerificationCodeRequest:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  auth.Tokens:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
    required:
    - accessToken
    - refreshToken
    type: object
  auth.VerifyEmailRequest:
    properties:
      code:
        type: string
      email:
        type: string
    required:
    - code
    - email
    type: object
  call.StartCallRequest:
    properties:
      callee_id:
        type: string
    required:
    - callee_id
    type: object
  call.StartCallResponse:
    properties:
      room_name:
        type: string
      token:
        type: string
    type: object
  httputil.ErrorBody:
    properties:
      code:
        type: string
      fields: {}
      message:
        type: string
    type: object
  httputil.ErrorResponse:
    properties:
      error:
        $ref: '#/definitions/httputil.ErrorBody'
    type: object
  livekit.TokenResponse:
    properties:
      token:
        type: string
    required:
    - token
    type: object
  message.GetPagingResponse:
    properties:
      messages:
        items:
          $ref: '#/definitions/model.Message'
        type: array
      nextCursor:
        type: string
    type: object
  model.Message:
    properties:
      content:
        type: string
      createdAt:
        type: string
      id:
        type: string
      roomID:
        type: string
      sender:
        $ref: '#/definitions/model.MessageSender'
    required:
    - content
    - createdAt
    - id
    - roomID
    - sender
    type: object
  model.MessageSender:
    properties:
      avatarUrl:
        type: string
      id:
        type: string
      username:
        type: string
    type: object
  model.Room:
    properties:
      id:
        type: string
      members:
        items:
          $ref: '#/definitions/model.RoomMember'
        type: array
      name:
        type: string
      slug:
        type: string
    required:
    - id
    - slug
    type: object
  model.RoomMember:
    properties:
      id:
        type: string
      roomID:
        type: string
      userID:
        type: string
    required:
    - id
    - roomID
    - userID
    type: object
  model.User:
    properties:
      avatarUrl:
        type: string
      email:
        type: string
      emailVerified:
        type: boolean
      id:
        type: string
      username:
        type: string
    required:
    - email
    - emailVerified
    - id
    - username
    type: object
  room.CreateRequest:
    properties:
      name:
        maxLength: 50
        minLength: 3
        type: string
    type: object
  room.CreateResponse:
    properties:
      slug:
        type: string
    required:
    - slug
    type: object
  room.ListResponse:
    properties:
      rooms:
        items:
          $ref: '#/definitions/model.Room'
        type: array
    required:
    - rooms
    type: object
  user.UpdateEmailRequest:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  user.UpdatePasswordRequest:
    properties:
      currentPassword:
        minLength: 6
        type: string
      newPassword:
        minLength: 6
        type: string
    required:
    - currentPassword
    - newPassword
    type: object
info:
  contact: {}
  title: Lunar API
  version: 1.0.0
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Login credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/auth.LoginCredentials'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.Tokens'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
      summary: Login a user
      tags:
      - auth
  /auth/logout:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
      summary: Logout a user
      tags:
      - auth
  /auth/refresh:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.Tokens'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
      summary: Refresh access token
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: Registration credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/auth.RegisterCredentials'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
      summary: Register a new user
      tags:
      - auth
  /auth/verify:
    post:
      consumes:
      - application/json
      parameters:
      - description: Verification credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/auth.VerifyEmailRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
      summary: Verify email
      tags:
      - auth
  /auth/verify/resend:
    post:
      consumes:
      - application/json
      parameters:
      - description: Email
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/auth.ResendVerificationCodeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
      summary: Resend verification code
      tags:
      - auth
  /call/start:
    post:
      consumes:
      - application/json
      parameters:
      - description: Call params
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/call.StartCallRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/call.StartCallResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Start a direct call
      tags:
      - call
  /livekit/token/{roomSlug}:
    get:
      parameters:
      - description: Room Slug
        in: path
        name: roomSlug
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/livekit.TokenResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get livekit access token
      tags:
      - livekit
  /rooms:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/room.ListResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
      security:
      - BearerAuth: []
      summary: List user rooms
      tags:
      - room
    post:
      consumes:
      - application/json
      parameters:
      - description: Room creation params
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/room.CreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/room.CreateResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Create a new room
      tags:
      - room
  /rooms/{roomSlug}:
    post:
      parameters:
      - description: Room Slug
        in: path
        name: roomSlug
        required: true
        type: string
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Join current user to room
      tags:
      - room
  /rooms/{roomSlug}/messages:
    get:
      parameters:
      - description: Room Slug
        in: path
        name: roomSlug
        required: true
        type: string
      - description: Limit
        in: query
        name: limit
        type: integer
      - description: Cursor
        in: query
        name: cursor
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/message.GetPagingResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
      security:
      - BearerAuth: []
      summary: List messages in a room
      tags:
      - message
  /users/me:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get current user
      tags:
      - user
  /users/me/avatar:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: Avatar file
        in: formData
        name: avatar
        required: true
        type: file
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Upload user avatar
      tags:
      - user
  /users/me/email:
    put:
      consumes:
      - application/json
      parameters:
      - description: Email update request
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/user.UpdateEmailRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Update user email
      tags:
      - user
  /users/me/password:
    put:
      consumes:
      - application/json
      parameters:
      - description: Password change request
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/user.UpdatePasswordRequest'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Change user password
      tags:
      - user
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
